### PR TITLE
Pause audio when video player is minimized

### LINKED ISSUE #460: Swiping away a playing video doesn't stop the audio
It's possible to get multiple simultaneous audio streams playing, which is confusing at best.

### Steps to reproduce

1. Start the app
2. Go to stream a video
3. Pinch to minimize it

### Expected behavior

1. Audio should stop with video

### Actual behavior

1. Audio stream continues in the background

### Environment

* iOS Version: 13.3
* raywenderlich.com App Version: Latest
* Device: iPhone

### PR DESCRIPTION
**Pull request by VegetarianZombie**
This is for bug: https://github.com/razeware/emitron-iOS/issues/460

This bug's root problem is that in some cases, SwiftUI does not deallocate the VideoPlaybackViewModel even though the model is set to nil. This means the audio will keep playing even though the video is dismissed. In those cases, the only way to stop the audio is to navigate back to the Library view or restart the app.

For a bandaid fix, I created a stop method in the view model. This will pause audio playback although the object still exists in memory. Objects will continue to accumulate until the user goes back to the Library view at which point all the objects are deallocated.

In cases where the behavior works as expected, the video will just pause before deallocation.

### CODE REVIEW

File: Emitron/Emitron/Data/ViewModels/VideoPlaybackViewModel.swift [hunk 1]
```diff
@@ -199,6 +199,12 @@ final class VideoPlaybackViewModel {
     self.shouldBePlaying = false
     self.player.pause()
   }
+
+  func stop() {
+    self.shouldBePlaying = false
+    self.player.pause()
+  }
+
```
Comment (sammyd) [inline Emitron/Emitron/Data/ViewModels/VideoPlaybackViewModel.swift]: Please address this SwiftLint warning.

**Review by sammyd — APPROVED** [review]
:+1: Looks good to me—just the SwiftLint issue to address and then this can be merged. Thanks!

File: Emitron/Emitron/Data/ViewModels/VideoPlaybackViewModel.swift (hunk 1 above)
Comment (sammyd) [reply Emitron/Emitron/Data/ViewModels/VideoPlaybackViewModel.swift]: I'll fix this and get it merged (=
